// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    // FormItem: typeof import('./src/components/PdForm/src/components/FormItem.vue')['default']
    // Pagination: typeof import('./src/components/PdTable/src/pagination/index.vue')['default']
    // PandoraContainer: typeof import('./src/components/PandoraContainer/index.vue')['default']
    PdContainer: typeof import('pandora2')['PdContainer']
    PdForm: typeof import('pandora2')['PdForm']
    PdTable: typeof import('pandora2')['PdTable']
  }
}
