// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Base: typeof import('./src/components/button/demo/base.vue')['default']
    Demo02: typeof import('./src/components/button/demo/demo02.vue')['default']
    FormItem: typeof import('./src/components/PdForm/src/components/FormItem.vue')['default']
    Pagination: typeof import('./src/components/PdTable/src/pagination/index.vue')['default']
    PandoraContainer: typeof import('./src/components/PandoraContainer/index.vue')['default']
    Preview: typeof import('./src/components/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/PdForm/src/index.vue')['default']
  }
}
