export type ComponentType =
  | 'Autocomplete'
  | 'Button'
  | 'Checkbox'
  | 'Cascader'
  | 'CheckboxGroup'
  | 'DatePicker'
  | 'Input'
  | 'InputNumber'
  | 'TimePicker'
  | 'TimeSelect'
  | 'Slider'
  | 'Select'
  | 'SelectOption'
  | 'Radio'
  | 'RadioGroup'
  | 'Switch'
  | 'Rate'
  | 'Divider'

export type NamePath = string | number | (string | number)[]
