// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PdContainer: typeof import('./packages')['PdContainer']
    PdForm: typeof import('./packages')['PdForm']
    PdTable: typeof import('./packages')['PdTable']
  }
}
