// Generated by unplugin-auto-import
export { }

declare global {
  const ref: typeof import('vue')['ref']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const computed: typeof import('vue')['computed']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onUpdated: typeof import('vue')['onUpdated']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const nextTick: typeof import('vue')['nextTick']
  const unref: typeof import('vue')['unref']
  const isRef: typeof import('vue')['isRef']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const defineComponent: typeof import('vue')['defineComponent']
  const h: typeof import('vue')['h']
}
